services:
  keycloak:
    image: keycloak/keycloak:24.0.5
    command: ["start-dev","--import-realm"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak-config.json:/opt/keycloak/data/import/keycloak-config.json