apiVersion: v1
kind: Secret
metadata:
  name: ingress-cert
  namespace: istio-system
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDHzCCAgegAwIBAgIUOLSVUGd7ycgdXJabl4CxG+/oRVcwDQYJKoZIhvcNAQEL
    BQAwFDESMBAGA1UEAwwJbG9jYWxob3N0MB4XDTI1MDgxMDE2Mzk1M1oXDTM1MDgw
    ODE2Mzk1M1owFDESMBAGA1UEAwwJbG9jYWxob3N0MIIBIjANBgkqhkiG9w0BAQEF
    AAOCAQ8AMIIBCgKCAQEA1JLp+8f7qa7JYPnc7QVLe6DAgoj6D3FzU07+7rD09zfe
    glRTMBekKrUCqNtbhRinGz8rKBpDKZqSAZu1Vy8gY4KDzhoSGZyePy8kZB6FbzYn
    rrvEm/IYdn1odksIPodFkozzjoLE2bGVbS4E9Qnz3f6KXVnb/0s8EN8SQYDNkoTq
    EShDUp4di16rsPTYa+xdq7XF5hyLs7EmigpXuoQWy1L2l2JwzncrkdaJlYWVKAIW
    wfGBcUD8BpSicGpuA+WaEQvHZa64yJm1bnhl7CpFZqK41dM5j5Q9s0KCdERvMw0t
    psBj4dnmffoclVg463+S99KLw1UNaTGwzwwX6HNgTQIDAQABo2kwZzAdBgNVHQ4E
    FgQUUC7ofVvec7vHkGydXXsL3khRA+cwHwYDVR0jBBgwFoAUUC7ofVvec7vHkGyd
    XXsL3khRA+cwDwYDVR0TAQH/BAUwAwEB/zAUBgNVHREEDTALgglsb2NhbGhvc3Qw
    DQYJKoZIhvcNAQELBQADggEBAAac3AeCmWyH1AzOPeLb+x9heY/Y+mS+N4Mtb2LU
    +HQ2QDA1PX8aKGunibmuPNfciPGLFrbNtMoImbgUzQ1w7lJL5Ks/bdnp9UFFK6iM
    xianPH1wBMXu5XUVJgICK3pP4hZtG6VGAJeketvn0wu4CugugLF5Eo3Cr5kRwL4m
    ceZw22AuOqs5r1nesZ0GxQcLvVIUjWolR+2i1nG3X8RTk/XjOrPZvO/4DS6+81eN
    IuRFEYnwR7473j64kXrMTuFYGVFWfNvxKB94kg957qKHi99q5QrCX7QKsaY0vr5F
    t7XFpvs4KjQ+SQpB3ji5sS8IIpFHHM5JQCSjBhxK4mv/HPg=
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDUkun7x/uprslg
    +dztBUt7oMCCiPoPcXNTTv7usPT3N96CVFMwF6QqtQKo21uFGKcbPysoGkMpmpIB
    m7VXLyBjgoPOGhIZnJ4/LyRkHoVvNieuu8Sb8hh2fWh2Swg+h0WSjPOOgsTZsZVt
    LgT1CfPd/opdWdv/SzwQ3xJBgM2ShOoRKENSnh2LXquw9Nhr7F2rtcXmHIuzsSaK
    Cle6hBbLUvaXYnDOdyuR1omVhZUoAhbB8YFxQPwGlKJwam4D5ZoRC8dlrrjImbVu
    eGXsKkVmorjV0zmPlD2zQoJ0RG8zDS2mwGPh2eZ9+hyVWDjrf5L30ovDVQ1pMbDP
    DBfoc2BNAgMBAAECggEAJO1flcRMENJC++Rz7z3F+tQ2VQbID9I4wz5cFWlqqJ6N
    Og09hUN6GowmyeAPUjvx3Y8X52fGho3qMrrSofJXGUpFLNLFFatqJxZAp17Q9byN
    4LIQKboA62aGNNR8emZD3P082yMW4K1ThKujo1CnC0eqUCSpzbvLU6/4qyXdsEey
    /1ZU18YUMco+bZc6XaH54LtPdVQI6iu2ePm7RDP1cYjVBYyDbzZagz2TFY3hqiYo
    EQ7pV2mckjzPoq+zUoDWryPgvEEHnJ9Fh6/CvqqAC0uIwDeP8fuAgECCfZsOOyTi
    gMGxXEvq7IvD+GX8JGPfnX627QSg5wPZQu1korHACQKBgQD080xhAVvHc7qIjDoY
    ZcUbmGUMwW5QSmprAK7luPaqs8Qx7dDBFMmG4DGfqdAQBADd+8PTgilo1NySkjOm
    cQYm6JCgVK5fKqoH3MWmExLTvMmZ2cGVFH6FEDy4AeioCEZyMhv6zb6CEKpFR7nH
    xJ1T7ek9RHxofndS+ZDpX7ifuQKBgQDeKbrZBcqgQT33WvOVwjndfttoiF4nNsfW
    7/lfMqPxy5TwfZ51f264yfMok2Dawwl2uAYbHqg5PGFOsF+3LquurfxpbQgQ2/7G
    KhSwjxyttj9dZpcg2HAFSWAczMZJo471Hk1OtUPePzX7RCc5imhNqGAl6INvOOJr
    ZexupV5HNQKBgQCXNi57X8RRjx6itrYSY5jXXS9cPXik9htVrNlLFPCpFkpSbDXH
    S9bQfUwE/WZkzKPgZVBRHHQFtAnqLXjXEcSzdjP51ezC8Op/6gjVacbgkRV+9U8s
    gbdM22YwTXVbbahXTJm7LRGi5zjFhe6o5LYenqqyWLnYI+Hzhf6wIpgteQKBgAuL
    w6gvwt4dRekrEum/lF5Mj36ZR7tl/3DOO/mUmiyg1fbBsJCOtORpqnd7YVc9N6qx
    2a9jIn8HAk+invbYOBf19t5LylWF+XG3Eigy59ynUhe6kzQjy36a16Hnio6dL3rR
    vlbO2N4eDuImIpu887rFe2m88ce//xRx0Z3WflXZAoGBAIySU+mrQPw8hzkPZtsX
    vJATH7Irzp23GvrZ8JB11YnuKgZc9Yxh7NKg7J5nia1Y/CnCX1u8AZs9AuUgKboR
    MHV0/FVaBIPZsfQESk+L7B6clgVzs3SOCeezPs7DradVDlq+RBVyuQINnZ32AM3v
    cYkVm8+wYuDetIeeVgsV9pAg
    -----END PRIVATE KEY-----
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: ingress-cert
      hosts:
        - "*"